
export const governorates = [
  { value: "New Cairo City", label: "Cairo" },
  { value: "Sheikh Zayed City", label: "Giza" },
  { value: "Qism El-Raml", label: "Alexandria" },
  { value: "Mansoura", label: "Dakahlia" },
  { value: "Zagazig", label: "Ash Sharqia" },
  { value: "Tanta", label: "Gharbia" },
  { value: "Port Fouad", label: "Port Said" },
  { value: "Asyut", label: "Asyut" },
  { value: "Sohag", label: "Sohag" },
  { value: "Kafr El Sheikh", label: "Kafr El Sheikh" },
  { value: "Shebeen El-Kom", label: "Menofia" },
  { value: "Damietta", label: "Damietta" },
  { value: "Suez", label: "Suez" },
  { value: "Markaz Kom Hamada", label: "Beheira" },
  { value: "New Minya City", label: "Minya" },
  { value: "Abu Simbel", label: "Aswan" },
  { value: "Benha", label: "Qalyubia" },
  { value: "Ismailia", label: "Ismailia" },
  { value: "Qena", label: "Qena" },
  { value: "Hurghada", label: "Red Sea" },
  { value: "Beni Suef", label: "Beni Suef" },
  { value: "Marsa Matruh", label: "Matrouh" },
  { value: "Al Faiyum City", label: "Faiyum" },
  { value: "Luxor", label: "Luxor" },
  { value: "Al Areesh", label: "North Sinai" },
  { value: "Al Wadi Al Gadid Desert", label: "New Valley" },
  { value: "Qesm Sharm Ash Sheikh", label: "South Sinai" },
]

